name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jupyterbook/jupyterbook-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: .
